### ISSUE TITLE
Server Crash Due To Ticking Entity

### ISSUE THREAD

**Issue by 5Ruler** [MerchantPug/apugli#14]
[crash-2022-07-03_21.50.59-server.txt](https://github.com/MerchantPug/apugli/files/9035650/crash-2022-07-03_21.50.59-server.txt)
<img width="705" alt="Screen Shot 2022-07-04 at 9 33 45 am" src="https://user-images.githubusercontent.com/108637116/177061006-123da9e1-661e-4ccd-afe3-790f8d395dda.png">
Asked in some other Discord why my server crashed when a member killed an Illusioner (a mob that the mod made). This was their response.

**Comment by ChrysanthCow** [comment]
Thanks for the report. I'll definitely get to fixing this.

**Comment by ChrysanthCow** [comment]
That was a relatively easy fix. My bad for not using the right class in the right location.

**Comment by ChrysanthCow** [comment]
Will probably release 1.8.0 soon as I have a few fixes for gamebreaking things implemented.
