### ISSUE TITLE
`Figura` mod incompatability with Elytra

### ISSUE THREAD

**Issue by CyraLX** [MerchantPug/apugli#22]
The Figura mod allows for custom avatars via Blockbench program, that program can create models that are grouped and some groups are Keywords that Figura uses to mimic vanilla behavior. What is broken are `RightElytra` and `LeftElytra` keywords that as the names suggest mimic parts of the Elytras when Apugli is loaded.
Figura version that is broken is `Figura 0.1.0 Pre-4` to `Figura 0.1.0 Pre-6`
A Figura report on this that has more specific info and an example avatar can be found here: https://discord.com/channels/805969743466332191/975571425295474708/999759885900206191

**Comment by ChrysanthCow** [comment]
I'm genuinely unsure as to what may cause this.

**Comment by ChrysanthCow** [comment]
It wasn't the code that you all talked about btw.

It's something else that I may need to dive deep into Apugli to fix.

**Comment by ChrysanthCow** [comment]
I'll see when I get the time to see what's causing this.

**Comment by ChrysanthCow** [comment]
Should be fixed in v1.9.1
