### ISSUE TITLE
eating items isn't working 

### ISSUE THREAD

**Issue by sparrowpaws** [MerchantPug/apugli#23]
So I've been using the mod [Mo's Grounded Origins](https://www.curseforge.com/minecraft/mc-mods/grounded-origins-fabric) on my Minecraft server and specifically with the Moth origin, which uses apugli:edible_item in order to make it so that paper, string, wool, leather, and books are edible. However, on my server, the eating animation/sound happens, but the items can't actually be consumed like they should be. The developer said that it works fine for them, so it's likely a mod compatibility issue, but I am not sure what could be causing it. 
I've attached a list of all the mods on my server, the Apugli version is 1.6.2. 
[modlist.txt](https://github.com/MerchantPug/apugli/files/9236722/modlist.txt)

**Comment by ChrysanthCow** [comment]
Apparently on 1.18.2, the edible item power is broken.

I'd try downgrading to a previous Apugli version since this version of the mod is no longer supported by me.

**Comment by ChrysanthCow** [comment]
https://github.com/MerchantPug/apugli/issues/9

Do you happen to have **Collective** installed?

**Comment by sparrowpaws** [comment]
Yes, Collective (Fabric) 4.27 is installed on the server.

**Comment by ChrysanthCow** [comment]
There's an incompatibility with that mod and this one unfortunately, I've made an issue on their GitHub because I think it's on their end.

**Comment by sparrowpaws** [comment]
ah, okay. thanks!

**Comment by ChrysanthCow** [comment]
Duplicate of #9
