### ISSUE TITLE
Incompatability with Nyf's spiders 2.0

### ISSUE THREAD

**Issue by netcore10** [MerchantPug/apugli#26]
Nyf's spiders issues leads to a broken discord link. Sent to Moonlight lib, but they said it was a mixin elsewhere.

https://mclo.gs/qvAZN94

https://mclo.gs/7JJELGb

After investigating, removing Apugli caused client to launch again.

**Comment by ChrysanthCow** [comment]
I don't think it's an incompat. I think it's an error that I made with a mixin during this update.

**Comment by MerchantPug** [comment]
I don't think it's purely an incompat. I think it's an error that I made with a mixin while trying to fix something.

**Comment by ChrysanthCow** [comment]
I'll revert the changes done there and I think it'll be fixed.

**Comment by ChrysanthCow** [comment]
Will get a patch out when I can.

**Comment by ChrysanthCow** [comment]
Okay, so more investigating was done and it happens whenever an explosion exists due to a mixin failing to apply.

**Comment by ChrysanthCow** [comment]
# Fixed in v1.11.1
