### ISSUE TITLE
hi, i have problem with connection to my fabric server (requires apugli version)

### ISSUE THREAD

**Issue by matveyvlone** [MerchantPug/apugli#29]
i installed apugli on client and on server, and when i try my best to join, i get this issue
![2023-02-27_22-45-22](https://user-images.githubusercontent.com/121692595/221667508-34efdad8-e1d5-4de8-8340-3521f6b387ea.png)
also, i use velocity proxy

**Comment by ChrysanthCow** [comment]
A few people have had issues with this, however, I don't really know how to fix it.

I'd just try the below which is quoted from my Discord
> Pug — 01/31/2023 3:39 AM
> I keep getting told that I need to install Apugli or TooManyOrigins on my server despite having either mod
>
> "performVersionCheck": false
> Include the above in your apugli.json/toomanyorigins.json config.
> 
> Delete your config files if you don't see this 

You'll also need to relaunch your server once you do this.

**Comment by matveyvlone** [comment]
> A few people have had issues with this, however, I don't really know how to fix it.
> 
> I'd just try the below which is quoted from my Discord
> 
> > Pug — 01/31/2023 3:39 AM
> > I keep getting told that I need to install Apugli or TooManyOrigins on my server despite having either mod
> > "performVersionCheck": false
> > Include the above in your apugli.json/toomanyorigins.json config.
> > Delete your config files if you don't see this
> 
> You'll also need to relaunch your server once you do this.

so... it doesn't help me, when i disable version check in apugli.json, parameter was deleted, it is so strange, and in origins.json i always disable version check, it doesn't help( maybe, you can add a fuction to disable version check in server apugli config? i think, it must help

**Comment by ChrysanthCow** [comment]
The weirdest part is that I have a disable version check inside the config. I guess I'll look into it next update.

**Comment by ChrysanthCow** [comment]
Sorry for the late response, this will be fixed in 2.0.0.

I took another look at the handshake packet code and I figured out what was up.

**Comment by ChrysanthCow** [comment]
Probably fixed in 2.0.0, please check and reopen this issue if it doesn't work.
