### ISSUE TITLE
Apugli causes crash render error with tinkers construct buckets and blood magic buckets.

### ISSUE THREAD

**Issue by Shido0** [MerchantPug/apugli#3]
Download tinkers construct 1.16.5 and mantle, blood magic 1.16.5, forge 36.2.31, apugli 1.16.5
Create a creative world and look up bu (if you want blood magic crash) and pat (for tinkers construct crash
the connected file is a crash report for tinkers construct 
also if you have jei the buckets simply not show up
[crash-2022-03-22_01.01.32-client.txt](https://github.com/MerchantPug/apugli/files/8322289/crash-2022-03-22_01.01.32-client.txt)
)

**Comment by MerchantPug** [comment]
I'll see what's up with this in a bit.

**Comment by MerchantPug** [comment]
I think I know the issue.

Forge handles fluids in a different way to Fabric, these mods use that method too.

**Comment by MerchantPug** [comment]
Fixed by doing the above.

Will be patched in Apugli 1.5.1.1

**Comment by MerchantPug** [comment]
Pushed v1.5.1.1, this update should this this issue.

Thanks for reporting this to me, I would've had no idea otherwise.
