### ISSUE TITLE
modify_enchantment_damage_dealt example from docs causes a crash

### ISSUE THREAD

**Issue by DaedalusGame** [MerchantPug/apugli#32]
Crashlog: https://gist.github.com/DaedalusGame/bdcac5d3963e788417dd0452de8f84a4

Using the example from [here](https://apugli.readthedocs.io/en/latest/types/power_types/modify_enchantment_damage_dealt/) on Forge 1.19.2 yields a crash, saying it can't find the "enchantment" tag in the json? Notably type "modify_enchantment_level" works just fine, not sure whats wrong here.

**Comment by ChrysanthCow** [comment]
Thank you for the report, I'll look into this when I'm available to do so.

**Comment by ChrysanthCow** [comment]
Okay, so I was using the wrong serializable data within the power on Forge. I'll double check every power to make sure they have the correct data associated with them rn.

**Comment by ChrysanthCow** [comment]
This will be fixed in the upcoming release of v2.0.4.
