### ISSUE TITLE
modify_enchantment_damage_dealt doesn't work

### ISSUE THREAD

**Issue by DaedalusGame** [MerchantPug/apugli#33]
Once again using the example from [here](https://apugli.readthedocs.io/en/latest/types/power_types/modify_enchantment_damage_dealt/) and forge 1.19.2, it doesn't crash anymore but twiddling with the values it also doesn't seem to do anything at all, the damage stays constant at its vanilla value.

I'm also not sure what its supposed to do, is it just a shorthand for modifying the damage but with filtering for the user's enchantment or does it actually mixin the damage modifier formula for sharpness/bane of arthropods/smite/...?

**Comment by ChrysanthCow** [comment]
On Forge, it modifies the damage through an event.

`base_value` is the damage at level 1. With any more levels, the modifier is applied as many times as more levels there are.

**Comment by ChrysanthCow** [comment]
Thank you for the report though, I should really stop assuming things work after one fix.

**Comment by ChrysanthCow** [comment]
I was accidentally setting the power to equal the modify enchantment damage taken amount, which would be 0 without any of those powers.

This has now been fixed.

**Comment by ChrysanthCow** [comment]
Fixed in v2.1.0
