### ISSUE TITLE
modify_enchantment_damage_taken crashes the game if given to another entity (?)

### ISSUE THREAD

**Issue by DaedalusGame** [MerchantPug/apugli#34]
Crashlog: https://gist.github.com/DaedalusGame/02093131962bbb4abe722ee969463fc8

I tested modify_enchantment_damage_taken with the same example as modify_enchantment_damage_dealt but swapped out the type, then i gave it to all entities with /power grant <x> @e and smacked an entity with a sharpness sword, crashing the game.

**Comment by ChrysanthCow** [comment]
I simply forgot a null check here, will be fixed in 2.0.6.

**Comment by ChrysanthCow** [comment]
Fixed in v2.1.0.
