### ISSUE TITLE
Entity Texture Overlay not working completely

### ISSUE THREAD

**Issue by GekidoLukas** [MerchantPug/apugli#35]
Hey, so I use Entity Texture Overlay for some clothing, but the option `render_player_outer_player` doesn't do anything sadly ^^"
When setting it to false, it still renders the outer layer.

Edit: `show_first_person` and other options also don't apply

**Comment by GekidoLukas** [comment]
Oh and I noticed, that the overlay added by the power won't change the angle when sneaking

**Comment by ChrysanthCow** [comment]
The docs have an error atm, you'll need `render_player_outer_layer`.

But I'll look into this later

**Comment by ChrysanthCow** [comment]
Mind if I ask what version and loader you're on?

**Comment by GekidoLukas** [comment]
I will test that real quick. 
And I am on Fabric 1.19.4

**Comment by GekidoLukas** [comment]
Ah yes, it works now, thanks a lot. 
However, the outer layer of the texture I am using still does not work properly when sneaking sadly ^^"
![2023-06-04_00 15 22](https://github.com/MerchantPug/apugli/assets/59490449/2d22e84c-1719-41d2-9d88-dafc4aa703bf)

**Comment by ChrysanthCow** [comment]
> Ah yes, it works now, thanks a lot. 
> However, the outer layer of the texture I am using still does not work properly when sneaking sadly ^^"
> ![2023-06-04_00 15 22](https://github.com/MerchantPug/apugli/assets/59490449/2d22e84c-1719-41d2-9d88-dafc4aa703bf)
> 

I'll look into making it work while you're sneaking when I'm available to do so, I've already started on a new update, so this should be fixed in that next update

**Comment by GekidoLukas** [comment]
Alright, thank you ^^

**Comment by ChrysanthCow** [comment]
It was only the jacket layer that was broken, this has now been fixed and will be released in Apugli v2.2.0
