### ISSUE TITLE
Crash with Mobs Ignore when trying to check for a power

### ISSUE THREAD

**Issue by GekidoLukas** [MerchantPug/apugli#37]
Hey, so wanted to have mobs ignore me unless they have a certain power. When dropping an item, this crashed my game since items can't have powers.
So I tried to check for living, but it still crashed.

This is my power:
```Json
{
    "type": "apugli:mobs_ignore",
    "mob_condition": {
      "type": "origins:living"
    },
    "bientity_condition": {
      "type": "origins:target_condition",
      "condition": {
        "type": "origins:power",
        "power": "mmpextras:enlightened",
        "inverted": true
      }
    }
  }
```

Crash Report: https://pastebin.com/6dCa4qVX

I think a check if the entity can have powers could fix it, but that is just a theory on my side.

I hope you can fix it.

**Comment by ChrysanthCow** [comment]
You probably noticed, but this doesn't seem to be on my end judging by the crashlog.

**Comment by GekidoLukas** [comment]
Yes I did, it seems to be a more general issue
