### ISSUE TITLE
apugli server crash 1.18.2 when using splash potion?

### ISSUE THREAD

**Issue by netcore10** [MerchantPug/apugli#38]
[crash-2023-06-19_23.03.13-server.txt](https://github.com/MerchantPug/apugli/files/11793481/crash-2023-06-19_23.03.13-server.txt)

**Comment by ChrysanthCow** [comment]
I'll check this once I'm on my pc

**Comment by ChrysanthCow** [comment]
Alright, this is a pretty easy fix, that will have to cross over to other versions of the mod.
