### ISSUE TITLE
`apugli:modify_enchantment_level` no longer works with Enchantments if their item is not currently being used

### ISSUE THREAD

**Issue by CyraLX** [MerchantPug/apugli#39]
Using the specified power on something like `minecraft:respiration` will not do anything unless the power holder has a helmet on. Same thing goes for `minecraft:fire_aspect`, if the power holder doesn't have an item in their main hand, it doesn't apply the enchantment anymore.

Example code:
```json
{
    "type": "apugli:modify_enchantment_level",
    "enchantment": "minecraft:fire_aspect",
    "modifiers": [
        {
            "operation": "add_base_early",
            "value": 3
        }
    ]
}
```
Tested on Apugli 2.4.3 on Minecraft 1.20.1

**Comment by ChrysanthCow** [comment]
Strange, because I thought that I made a check for this.

**Comment by ChrysanthCow** [comment]
I'll look into it now.
