### ISSUE TITLE
Edible Item animation doesn't work.

### ISSUE THREAD

**Issue by WaterCraver** [MerchantPug/apugli#41]
I'm using the `edible_item` powertype and it kinda works.
Almost everything functions as normal except when I right-click it doesn't actually _eat_ the item, it just plays a slowed-down version of the interact animation (the one where the item drops down and comes back up).

I've looked through the other issues and the only ones similar to mine are caused by collective, which I don't have installed.
Are there any other mod incompatibilities? I can send my mods list if you'd like.

**Comment by ChrysanthCow** [comment]
I don't know about any other mod incompatibilities, may I please have a mod list?

**Comment by WaterCraver** [comment]
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Inventory HUD+ (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[WI Zoom (by alexander9892)](https://www.curseforge.com/minecraft/mc-mods/wi-zoom)
[Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[cAn i MiNe thIS bLOCk? (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/can-i-mine-this-block)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Nbt Crafting (Fabric) (by Siphalor)](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Apugli (by MerchantPug (That's you!))](https://www.curseforge.com/minecraft/mc-mods/apugli)
[Customizable Player Models (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/custom-player-models-fabric)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[Impersonate (by PyrofabTheModsmith)](https://www.curseforge.com/minecraft/mc-mods/impersonate)
[Extra Origins (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/extra-origins)
[Axolotl Bucket Fix (by colderlavalamp)](https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix)
[Multiworld (Fabric & Forge) (by theisaiahp)](https://www.curseforge.com/minecraft/mc-mods/multiworld-mod)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Better Ping Display [Fabric] (by Quintinity)](https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric)
[Origins (Fabric) (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Cherished Worlds (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/cherished-worlds)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Skin Swapper (by cobrasrock)](https://www.curseforge.com/minecraft/mc-mods/skin-swapper)
[Summoning Rituals (by Relentless)](https://www.curseforge.com/minecraft/mc-mods/summoningrituals)
[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Origins: Classes (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[Effective (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/effective)
[PaperDoll (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/paperdoll)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[ToolTipFix (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Satin API (by PyrofabTheModsmith)](https://www.curseforge.com/minecraft/mc-mods/satin-api)
[Eating Animation [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[Open Loader (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/open-loader)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[megane (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/megane)
[Client Tweaks (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Farsight [Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight-fabric)
[Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Vivecraft (by Ferri_Arnus)](https://www.curseforge.com/minecraft/mc-mods/vivecraft)
[Custom Entity Models (CEM) (by dorianpb)](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)

**Comment by WaterCraver** [comment]
I found the issue.
I had to specify the `use_action`, it works now.
I thought it defaulted to `eat`, but that doesn't seem to be the case.

I'll close the issue now, sorry for wasting your time.

**Comment by ChrysanthCow** [comment]
I should still probably set a default, which will be present in the next update.
