### ISSUE TITLE
`apugli:modify_enchantment_level` still doesn't work if Item Stack is missing with some enchantments

### ISSUE THREAD

**Issue by CyraLX** [MerchantPug/apugli#42]
Specified Power fails to apply the enchantment modifier to the power holder if the power holder has no item stack at all in any of their Equipment Slots.

Example:
Lets say I have this Power on a Player:
```json
{
    "type": "apugli:modify_enchantment_level",
    "enchantment": "minecraft:respiration",
    "modifier": {
        "operation": "add_base_early",
        "value": 3
    }
}
```
This Power only grants III levels of Respiration to the player IF they hold at least an Item Stack in their Main Hand, Off Hand or Armor Slot. If none of them are filled the power fails to add the needed enchantment level modifications.

**Comment by ChrysanthCow** [comment]
Okay, what the fuck

**Comment by ChrysanthCow** [comment]
For some context, I tested it on Fire Aspect, and yeah, that worked.

**Comment by ChrysanthCow** [comment]
I think it's not working because of another reason entirely.

I made a change to the logic that broke the power last update.

I'll just revert this.

**Comment by ChrysanthCow** [comment]
I've managed to fix this, it'll be fixed in the next patch.
