### ISSUE TITLE
Crash when logging onto server [1.19.2]

### ISSUE THREAD

**Issue by NyakoFox** [MerchantPug/apugli#44]
![image](https://github.com/MerchantPug/apugli/assets/87289390/2d8a9b9a-3cdf-4793-8694-488d1d37befb)

Unsure about specifics, all I know is there's a crash caused by this library. Is this a known thing?

**Comment by NyakoFox** [comment]
We have a create machine that automatically breeds cows, and I suspect that's the issue -- create machines do not have Origins powers I assume, or at least don't have component providers.

**Comment by ChrysanthCow** [comment]
Thanks for the report, I'll definitely fix this in the next upcoming update.

**Comment by ChrysanthCow** [comment]
Looked into my code, and it seems to have been fixed already. What Apugli verison are you on?

**Comment by NyakoFox** [comment]
Should be 2.4.5, which seems to be latest for 1.19.2.

**Comment by ChrysanthCow** [comment]
Ah nevermind, I understand the issue now.

**Comment by ChrysanthCow** [comment]
Re -opening this until the update is actually released.
