### ISSUE TITLE
Apugli 2.5.5 breaks any zoom mod 1.20.1

### ISSUE THREAD

**Issue by WaterCraver** [MerchantPug/apugli#46]
Whenever I update to apugli 2.5.5 any zoom mod (I've tested WI Zoom, Zoomify, and Logical Zoom.) completely breaks.
Any effect (such as decreased sensitivity or cinematic camera.) happens, just the actual zooming doesn't.

**Comment by ChrysanthCow** [comment]
I'll look into this at some point. This probably has to do with the new `modify_fov` power.

**Comment by ChrysanthCow** [comment]
Will be fixed in 2.5.1
