### ISSUE TITLE
Latest Version Breaks Simply Swords

### ISSUE THREAD

**Issue by kenbaird13** [MerchantPug/apugli#51]
The latest version of TooManyOrigins, beta 13, breaks Simply Swords. If you hold a 2-handed sword with an item in your offhand, that item is deleted.

**Comment by ChrysanthCow** [comment]
I'm very unsure how this would happen, but I'll see what's up here.

**Comment by ChrysanthCow** [comment]
I've just moved this issue over to Apugli, as it should not be TooManyOrigins that's causing it.

**Comment by ChrysanthCow** [comment]
The problematic code seems to be on Better Combat's end, as they're setting an itemstack to be empty somewhere in their code.
