### ISSUE TITLE
Edible Item not consuming item when in stacks with return stack object

### ISSUE THREAD

**Issue by SuppremeBlueX** [MerchantPug/apugli#64]
I have the following code:
```json
{
    "type": "apugli:edible_item",
    "item_condition": {
        "type": "origins:ingredient",
        "ingredient": {
            "item": "minecraft:soul_sand"
        }
    },
    "food_component": {
        "hunger": 4,
        "saturation": 0.25,
        "meat": false
    },
    "use_action": "eat",
    "return_stack": {
        "item": "minecraft:soul_soil",
        "amount": 1
    },
    "name": "\u00A72\u00A7nSoul Slurp",
    "description": "You can drink souls out of soul sand to replenish your food."
}
```

The issue I'm having is when I have more than 1 soul sand in a stack and eating it, it will create the soul soil without consuming the soul sand. However, it does give me food and saturation. Is this something I'm doing wrong or a problem with the return_stack object as without that, it consumes the soul sand even in stacks.

**Comment by ChrysanthCow** [comment]
Hi, which MC version are you on?

**Comment by SuppremeBlueX** [comment]
1.20.1 Fabric. I forgot to include that, sorry.

Edit: I can be more specific. Apugli-2.9.1+1.20.1-fabric.jar

**Comment by ChrysanthCow** [comment]
> 1.20.1 Fabric. I forgot to include that, sorry.
> 
> Edit: I can be more specific. Apugli-2.9.1+1.20.1-fabric.jar

Thanks. I'll look into this at a later date, I'm busy with other mods atm.

**Comment by ChrysanthCow** [comment]
Fixed by not copying the stack used to eat.
