### ISSUE TITLE
Particle power crashes the game with Apugli installed

### ISSUE THREAD

**Issue by Kawatt** [MerchantPug/apugli#66]
Power used: 
[sparkles.json](https://github.com/MerchantPug/apugli/files/14313667/sparkles.json)

Crash report: 
[crash-2024-02-16_16.49.01-server.txt](https://github.com/MerchantPug/apugli/files/14313672/crash-2024-02-16_16.49.01-server.txt)

Logs: 
[latest.log](https://github.com/MerchantPug/apugli/files/14313677/latest.log)

The crash happens when loading the world for the first time, will not cause a crash if the power is added to the origin's power list and then reloaded

**Comment by ChrysanthCow** [comment]
That's insanely weird, no clue why it'd do that.

**Comment by ChrysanthCow** [comment]
I likely won't be getting a fix out for a bit, mainly because I'm just kinda tired of working on Origins related stuff 😐. Sorry for the inconvenience.

**Comment by ChrysanthCow** [comment]
Looking into this now, the same bug with a different cause was reported on my Discord.

It should be an easy fix.
