### ISSUE TITLE
Calming Aura isn't working, at all.

### ISSUE THREAD

**Issue by Twisted-Code** [MerchantPug/apugli#79]
# Description 
 I selected Swarm, which has the Calming Aura effect. However, I'm still getting the usual breeding cooldown instead of 1 second, and as far as I can tell cows shouldn't have the tag to ignore the effect, right? I at least checked that this specific Cow didn't with the tags command (see attached screenshot).
# expected behavior
passive mobs should be instantly rebreedable "like it says on the tin"
# actual behavior
The power just straight up doesn't work, even when I only have origins & TMO
# repro
1. Pick Swarm as your origin
2. spawn 2 cows
3. give yourself some wheat
4. breed the cows
5. bug occurs when you try to breed them again within the vanilla 5 minute cooldown
# Environment & Versions
Prism Launcher: 8.3
Forge: 47.2.32
Caelus: caelus-forge-3.2.0+1.20.1.jar
Origins (Forge): origins-forge-1.20.1-1.10.0.9-all.jar
TooManyOrigins: TooManyOrigins-1.1.2+1.20.1-forge 
# Additional information
The below is a screenshot I took from the pack I was playing, but I get the same result when I isolate just TMO and Origins in a Forge instance. Note the cooldown and absence of any tags (Although I suspect that command only reads the individual entity data) on the mob I'm looking at.
![2024-06-21_08 18 23](https://github.com/MerchantPug/apugli/assets/7110033/620d71ba-4f7b-4588-9e0b-1c69f3ba402f)

**Comment by ChrysanthCow** [comment]
I will look into this eventually, I think that this is just me forgetting to test this power type on Forge.

**Comment by ChrysanthCow** [comment]
Turns out I hadn't implemented this on Forge. I'll implement this across the versions I'm bugfixing.

**Comment by ChrysanthCow** [comment]
It was actually a Forge event moment, I thought the Forge event was ran after love ticks were set, but apparently not.
