### ISSUE TITLE
Edible Item Seems to be consuming two when possible, but not EATING two.

### ISSUE THREAD

**Issue by tillasiren** [MerchantPug/apugli#81]
[eat_bone.json](https://github.com/user-attachments/files/16594793/eat_bone.json)
[salamander_metal_digestion.json](https://github.com/user-attachments/files/16594794/salamander_metal_digestion.json)

Minecraft Version: 1.20.1
Origins Forge Port(1.10.0.9), with Apugli (Apugli-2.10.2+1.20.1-forge)

I have included two of the powers I have attempted that both are showing the issue. Both are on origins with modify food powers (mentioning because I looked and saw a prior bug report calling that out possibly). I have tested with adding/removing bits such as the consume and item use action parts. Or removing the modify food powers from the origin. Both yielded no different results.
In addition I have noticed some inconsistency in on multiple occasions the edible item power seemed to produce a one click and then it would consume the item after a second effect with no animation like one would expect. Though in the vast majority of times it is eating with the normal animation. As of now I am at a loss for a way to prevent this occuring so I will simply be adding a disclaimer when I introduce people to the origins. I hope for and look forward to any potential fixes.

**Comment by ChrysanthCow** [comment]
Hi, could I potentially have a gif/recording of what I need to look for?

**Comment by tillasiren** [comment]
https://drive.google.com/file/d/1dvRVGbPLBi6MIaOoLo9t5H0Jq4iwEMsW/view?usp=sharing
You should be able to get the video off that, to large to upload even a 27 second video on github apparently.
As mentioned in the title when its a stack of one it eats things fine, but when its a normal stack it seems to think it should take two of the item. I did have a few times in testing where it did only take one item with the copper ore in the salamander power... but I could not intentionally replicate it when I noticed it.

**Comment by ChrysanthCow** [comment]
Thank you! Will look in a bit.

**Comment by ChrysanthCow** [comment]
Okay, so this is actually not a problem with Apugli.

This seems to be a problem with your powers, this is because `consume` does not operate along with the Edible Item power.
Your best bet will be to have a check for if the stack is 2 or greater, and then run a better edible item power instead.

I will not be changing this, because hardcoding this behavior is just a bad idea.
